# Generated by Django 4.2.16 on 2026-04-17 07:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sentiment', models.CharField(choices=[('like', 'Like'), ('neutral', 'Neutral'), ('dislike', 'Dislike')], default='like', max_length=10)),
                ('level', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='preferences/')),
                ('image_source_type', models.CharField(choices=[('uploaded', 'Uploaded'), ('default', 'Default')], default='default', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferences', to='categories.category')),
            ],
            options={
                'verbose_name': 'Preference Entry',
                'verbose_name_plural': 'Preference Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
