# Generated by Django 4.2.16 on 2026-04-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('relation', models.CharField(choices=[('self', 'Self'), ('friend', 'Friend'), ('brother', 'Brother'), ('sister', 'Sister'), ('mother', 'Mother'), ('father', 'Father'), ('colleague', 'Colleague'), ('partner', 'Partner'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_self_profile', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
